[FIX]: Build error for fourcc; Check description
error: ‘fourcc’ is not a member of ‘cv::VideoWriter’;
Reverted to original from a push to master by fnoop which broke the build with the above error. To be analyzed.